apiVersion: classification.nexuspro.io/v1
kind: FeatureRegistry
metadata:
  name: ose-feature-registry
  version: "∞.7"
spec:
  features:
    - id: ai-ml
      name: "Artificial Intelligence & Machine Learning"
      category: "ai"
      icon: "🧠"
      description: "AI models, ML pipelines, neural networks, and inference services"
      tags: ["ai", "ml", "neural", "deep-learning", "llm", "inference"]
      mesh_service: "ai-orchestrator"
      namespace: "ose-ai-ml"
      default_plugins:
        - "tensorflow-svc"
        - "pytorch-svc"
        - "llm-gateway"
        - "vector-db"
        - "model-registry"
    
    - id: web3-blockchain
      name: "Web3 & Blockchain"
      category: "web3"
      icon: "🔗"
      description: "Blockchain nodes, smart contracts, and decentralized applications"
      tags: ["blockchain", "web3", "smart-contracts", "defi", "nft", "ethereum"]
      mesh_service: "blockchain-gateway"
      namespace: "ose-web3"
      default_plugins:
        - "ethereum-node"
        - "smart-contract-verifier"
        - "ipfs-gateway"
        - "wallet-service"
    
    - id: cloud-native
      name: "Cloud Native Platform"
      category: "cloud"
      icon: "☁️"
      description: "Kubernetes orchestration, serverless functions, and cloud services"
      tags: ["kubernetes", "serverless", "microservices", "containers", "docker"]
      mesh_service: "cloud-controller"
      namespace: "ose-cloud"
      default_plugins:
        - "k8s-operator"
        - "serverless-runtime"
        - "service-mesh"
        - "cloud-autoscaler"
    
    - id: data-engineering
      name: "Data Engineering & Analytics"
      category: "data"
      icon: "📊"
      description: "Data pipelines, stream processing, analytics, and databases"
      tags: ["data", "analytics", "database", "etl", "bi", "streaming"]
      mesh_service: "data-pipeline"
      namespace: "ose-data"
      default_plugins:
        - "data-ingestor"
        - "stream-processor"
        - "olap-engine"
        - "data-catalog"
    
    - id: devops-platform
      name: "DevOps & CI/CD"
      category: "devops"
      icon: "🚀"
      description: "Continuous integration, deployment automation, and infrastructure"
      tags: ["devops", "cicd", "monitoring", "infrastructure", "automation"]
      mesh_service: "devops-orchestrator"
      namespace: "ose-devops"
      default_plugins:
        - "ci-runner"
        - "cd-deployer"
        - "monitoring-stack"
        - "security-scanner"
    
    - id: security-platform
      name: "Security & Compliance"
      category: "security"
      icon: "🛡️"
      description: "Security scanning, compliance audits, and identity management"
      tags: ["security", "compliance", "auth", "encryption", "audit"]
      mesh_service: "security-gateway"
      namespace: "ose-security"
      default_plugins:
        - "auth-service"
        - "encryption-proxy"
        - "audit-logger"
        - "threat-detector"
    
    - id: system-ops
      name: "System Operations"
      category: "system"
      icon: "⚙️"
      description: "System discovery, optimization, configuration, and management"
      tags: ["system", "discovery", "optimization", "configuration", "management"]
      mesh_service: "system-controller"
      namespace: "ose-system"
      default_plugins:
        - "discovery-service"
        - "optimization-service"
        - "terminal-config"
        - "factory-reset"
        - "reinstallation"
    
    - id: observability
      name: "Observability & Monitoring"
      category: "monitoring"
      icon: "📈"
      description: "Metrics collection, logging, tracing, and alerting"
      tags: ["monitoring", "metrics", "logging", "tracing", "alerting"]
      mesh_service: "observability-hub"
      namespace: "ose-monitoring"
      default_plugins:
        - "metrics-collector"
        - "log-aggregator"
        - "trace-collector"
        - "alertmanager"
  
  classification_rules:
    - match: ".*(ai|ml|neural|tensor|pytorch|llm|model).*"
      feature: "ai-ml"
      confidence: 0.9
    
    - match: ".*(blockchain|web3|smart.?contract|defi|nft|ethereum).*"
      feature: "web3-blockchain"
      confidence: 0.85
    
    - match: ".*(cloud|kubernetes|k8s|serverless|container|docker).*"
      feature: "cloud-native"
      confidence: 0.8
    
    - match: ".*(data|database|analytics|pipeline|etl|stream).*"
      feature: "data-engineering"
      confidence: 0.8
    
    - match: ".*(devops|ci.?cd|deploy|jenkins|gitlab).*"
      feature: "devops-platform"
      confidence: 0.85
    
    - match: ".*(security|auth|encrypt|compliance|audit).*"
      feature: "security-platform"
      confidence: 0.9
    
    - match: ".*(discovery|optimization|config|reset|reinstall).*"
      feature: "system-ops"
      confidence: 0.85
    
    - match: ".*(monitor|metric|log|trace|alert|observe).*"
      feature: "observability"
      confidence: 0.8
  
  mesh_integration:
    auto_register: true
    sidecar_injection: true
    traffic_policies: true
    observability: true
    security_policies: true
    global_namespace: "ose-registry"
